# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[('M.', 'M.'), ('MME', 'Mme')], default='M.', max_length=3, verbose_name='Civilité')),
                ('birth_name', models.CharField(max_length=255, verbose_name='Nom de naissance')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom d'usage ou marital")),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance ')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Ville de naissance')),
                ('birth_country', django_countries.fields.CountryField(max_length=2, verbose_name='Pays de naissance')),
                ('mail', models.EmailField(max_length=255, verbose_name='Mail')),
                ('street_type', models.CharField(choices=[('Boulevard', 'Boulevard'), ('Avenue', 'Avenue'), ('Cours', 'Cours'), ('Place', 'Place'), ('Rue', 'Rue'), ('Route', 'Route'), ('Voie', 'Voie'), ('Chemin', 'Chemin'), ('Square', 'Square'), ('Impasse', 'Impasse'), ('Rond-point', 'Rond-point'), ('Quai', 'Quai')], default='Rue', max_length=30, verbose_name='Type de rue')),
                ('street_number', models.CharField(max_length=30, verbose_name='Numéro de rue')),
                ('street', models.CharField(max_length=30, verbose_name='Rue')),
                ('comp_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complément 1')),
                ('comp_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complément 2')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Code postal')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
            ],
        ),
    ]
